### ISSUE TITLE
TODO list of static linking support

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/mcfgthread#29]
- [ ] Cleanup of thread-local storage.
In the case of dynamic linking this is done in response to the `DLL_THREAD_DETACH` notification.
Fiber local storage is not an option because code that expects TLS objects to be preserved upon `SwitchToFiber()` will be broken.

- [ ] Initialization of the thread library before any other code.
In the case of dynamic linking this is done in response to the `DLL_PROCESS_ATTACH` notification.
Due to a Windows bug a TLS callback is not invoked with such a notification if the executable was linked against _only_ KERNEL32 and NTDLL. In order to cover all cases, we must modify MinGW-w64 startup code and perform the initialization before the `__main()` function from **libgcc**.

- [ ] Cleanup of the thread library.
In the case of dynamic linking this is done in response to the `DLL_PROCESS_DETACH` notification.
Use of a DLL entry point function or a TLS callback is essential for the cleanup to be performed upon a call to the `exit()` or `ExitProcess()` function, either of which is out of our scope.

- [ ] Find a solution to [GCC PR80883](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80883).
Is it possible to define this function in every DLL?

- [ ] Use named shared memory to allocate storage for process-wide objects.

**Comment by lhmouse** [comment]
If any of you have interest it is worth having a look at how static linking is implemented [in MCFCRT](https://github.com/lhmouse/MCF/tree/master/MCFCRT/src/pre). In reality these files are compiled into two **static** libraries: `libmcfcrt-pre-exe.a` (from all files without `dll.c`) and `libmcfcrt-pre-dll.a` (from all files without `exe.c`, apparently).

Note that MCFCRT handles TLS differently than mcfgthread in a way that TLS is module-specific instead process-specific. This is required for guaranteed destructor calls of TLS objects when `FreeLibrary()` is called to unload a DLL dynamically.

**Comment by lhmouse** [comment]
This has been solved by d8198e229f4af854c4c98850cdff0f25dc089575.
